config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cocktails#index'
  mount Attachinary::Engine => "/attachinary"
  resources :cocktails do
    resources :reviews, only: [:new, :create]
    resources :doses, :shallow => true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_attachment :photo
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :ingredient, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

private

  def set_cocktail
   @cocktail = Cocktail.find(params[:id])
  end


  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.new(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = @cocktail.reviews.new(review_params)
    if @review.save
      redirect_to @cocktail
    else
      render 'cocktails/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :cocktail_id, :author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/edit.html.erb
<div class="container text-center">
<h2> Edit cocktail</h2>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="container text-center">
<h1>Cocktails</h1>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://image.freepik.com/free-vector/abstract-background-with-colorful-geometric-shapes_23-2147616351.jpg'); background-size: cover">
          <% if cocktail.photo? %>
            <%= cl_image_tag cocktail.photo.path, width: 200, height: 200, crop: :fill %>
          <% end %>
          <h2><%= link_to cocktail.name.capitalize, cocktail_path(cocktail) %></h2>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container text-center">
<h2> Add a new cocktail</h2>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container text-center">
  <h2><%= @cocktail.name.capitalize %></h2>
  <p><%= link_to "edit", edit_cocktail_path(@cocktail), class: "btn btn-default" %></p>
  <% if @cocktail.photo? %>
    <%= cl_image_tag @cocktail.photo.path, width: 200 %>
  <% end %>
  <h3><%= link_to "Add dose", new_cocktail_dose_path(@cocktail), class: "btn btn-default" %></h3>
  <% @cocktail.doses.each do |dose| %>
    <p><%= dose.description %> of <%= dose.ingredient.name %> <%= link_to "❌", dose_path(dose), method: :delete %></p>
  <% end %>
  <hr>
  <div class="review">
    <h3>Reviews</h3>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <% @cocktail.reviews.each do |review| %>
          <blockquote>
           <p><%= review.content %></p>
            <small><%= review.author %></small>
          </blockquote>
        <% end %>
        <hr>
        <p><b>ADD YOUR REVIEW !</b></p>
        <hr>
        <%= simple_form_for [@cocktail, @review] do |f| %>
          <%= f.input :author %>
          <%= f.input :content %>
          <%= f.button :submit %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="padded">

  </div>

</div>

app/views/doses/new.html.erb
<div class="container text-center">
<h2> Add a new dose</h2>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "🍸 MrCocktail", cocktails_path, id: "home_link" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Button (call-to-action) -->
    <%= link_to "Add a cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <%= link_to "Add", new_cocktail_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>